turning makefile from fn to var

diff --git a/deps b/deps
--- a/deps
+++ b/deps
@@ -9,13 +9,7 @@ function deps() {
     setopt extendedglob
     fc -R
     
-    function makefile() {
-	local MAKEFILE=$(print -l (../)#Makefile(:a) | head -n1) 2>/dev/null
-	[[ ! -f "$MAKEFILE" ]] && echo "Makefile not found. Use $(basename "$0") init." 1>&2 && exit 1
-	echo "$MAKEFILE"
-    }    
-
-    local function parse_recipe() {
+    local parse_recipe=function parse_recipe {
 	local -U DEPENDENCIES=()
 	local IFS=$IFS')(><|'
 	for D in "${=2}"; do
@@ -29,6 +23,16 @@ function deps() {
     local CMD="$1"
     [[ $# -ne 0 ]] && shift
 
+    # Find Makefile for subcommands that require it
+    case "$CMD" in
+	-h|--help|help|init);;
+	*)
+	    local MAKEFILE=$(print -l (../)#Makefile(:a) | head -n1) 2>/dev/null
+	    [[ ! -f "$MAKEFILE" ]] && echo "Makefile not found. Use $(basename "$0") init." 1>&2 && return 1
+	    ;;
+    esac
+
+    # Parse the main subcommand
     case "$CMD" in
 
 	add) #[FILE...], Scans history to determine the recipe that created each FILE (looks for ">"). Dependencies are automatically detected based on currently existing filenames mentioned in the recipe. Use set to add a recipe explicitly if these heuristics fail.
